### ISSUE TITLE
uniapp自定义组件编译模式遇到不支持安全随机数生成

### ISSUE THREAD

**Issue by JavinYang** [lipingruan/fucking-util-signature-uni#1]
HBuilderX2.3.3.20190923 最近uniapp建议使用自定义组件编译模式2019-11月之后将不再更新非自定义模式，但是在自定义模式下会报错如下：

00:35:28.238  thirdScriptError
00:35:28.238 Error during encryption. Original error: Error: Secure random number generation is not supported by this browser.
00:35:28.238 Use Chrome, Firefox or Internet Explorer 11;at api request success callback function
00:35:28.238 $$encryptKey
00:35:28.238 encrypt
00:35:28.238 rsaEncrypt_
00:35:28.238 success
00:35:28.238 app-service.js:3:418570
00:35:28.239 app-service.js:3:210301
00:35:28.239 app-service.js:3:95992
00:35:28.239 Xe@app-service.js:3:172466
00:35:28.239 app-service.js:3:282840
00:35:28.239 emit@app-service.js:3:203433
00:35:28.239 Ui@app-service.js:3:283350
00:35:28.239 app-service.js:3:283987
00:35:28.239 app-service.js:3:164381
00:35:28.239 subscribeHandler@app-service.js:3:2164
00:35:28.239 C@app-service.js:2:4946
00:35:28.239 Xt@app-service.js:2:34142
00:35:28.239 app-service.js:2:34957
00:35:28.239 consume@weex-main-jsfm.js:1:1263
00:35:28.239 map@[native code] __ERROR 

我找了相关的回答https://ask.dcloud.net.cn/question/73832

希望能做一下新的支持，感谢。

**Comment by lipingruan** [comment]
好的我先研究一下------------------ 原始邮件 ------------------
发件人: "JavinYang"<notifications@github.com>
发送时间: 2019年9月29日(星期天) 凌晨0:53
收件人: "lipingruan/fucking-util-signature-uni"<fucking-util-signature-uni@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [lipingruan/fucking-util-signature-uni] uniapp自定义组件编译模式遇到不支持安全随机数生成 (#1)



HBuilderX2.3.3.20190923 最近uniapp建议使用自定义组&#x4EF6;编译模式2019-11月之后将不再更新非自定义模式，但是在自定义模式下会报错如下：
 
00:35:28.238  thirdScriptError
 00:35:28.238 Error during encryption. Original error: Error: Secure random number generation is not supported by this browser.
 00:35:28.238 Use Chrome, Firefox or Internet Explorer 11;at api request success callback function
 00:35:28.238 $$encryptKey
 00:35:28.238 encrypt
 00:35:28.238 rsaEncrypt_
 00:35:28.238 success
 00:35:28.238 app-service.js:3:418570
 00:35:28.239 app-service.js:3:210301
 00:35:28.239 app-service.js:3:95992
 00:35:28.239 Xe@app-service.js:3:172466
 00:35:28.239 app-service.js:3:282840
 00:35:28.239 emit@app-service.js:3:203433
 00:35:28.239 Ui@app-service.js:3:283350
 00:35:28.239 app-service.js:3:283987
 00:35:28.239 app-service.js:3:164381
 00:35:28.239 subscribeHandler@app-service.js:3:2164
 00:35:28.239 C@app-service.js:2:4946
 00:35:28.239 Xt@app-service.js:2:34142
 00:35:28.239 app-service.js:2:34957
 00:35:28.239 consume@weex-main-jsfm.js:1:1263
 00:35:28.239 map@[native code] __ERROR
 
我找了相关的回答https://ask.dcloud.net.cn/question/73832
 
希望能做一下新的支持，感谢。
 
&mdash;

**Comment by JavinYang** [comment]
我检查了fucking-util-signature-uni/lib/sha256.js 中的代码，其中的19494行和19585行都已经进行了支持性的平台判断没有问题。我从新npm install了fucking-util-signature-all，覆盖了之前的文件之后一切正常。之前很是奇怪不管我怎么修改sha256.js文件中的内容UniApp/projectName/unpackage/dist/dev/app-plus/app-config.js下这个文件编译出的结果永远相同，替换之后就好了。可能我升级HBuildX版本以后出现了一些bug。
-

**Comment by JavinYang** [comment]
我检查了fucking-util-signature-uni/lib/sha256.js中的代码，其中的19494行和19585行已经进行了支持性的平台判断没有问题。我从新npm install了fucking-util-signature-all，覆盖了之前的文件之后一切正常。之前很是奇怪不管我怎么修改sha256.js文件中的内容/UniApp/projectName/unpackage/dist/dev/app-plus/app-service.js下这个文件编译出的结果永远相同，替换之后就好了。可能我升级HBuildX版本以后出现了一些buf。

**Comment by lipingruan** [comment]
有时候HBuilder缓存没更新, 重启调试服务或者删除node_modules重新安装就好.
