### ISSUE TITLE
使用nvue的情况下，引入会出错。

### ISSUE THREAD

**Issue by JavinYang** [lipingruan/fucking-util-signature-uni#2]
使用nvue的情况下引入下面的代码会导致一些奇怪的错误
let Signature = require("fucking-util-signature-all");
我在ios运行并打开引入了上面代码的页面之后，会导致页面什么画面都看不到。并且在控制台中并没有报错。
不引入它能看到正常画面显示。
我引入自己写的一个js文件是没有问题的。
不使用nvue在vue模式下一切正常，我不太清楚问题出在哪里。

**Comment by lipingruan** [comment]
好的, 我白天调试一下.

**Comment by lipingruan** [comment]
@JavinYang 问题已找到

目前Hbuilder条件编译有bug, 
可以直接用 `fucking-util-signature-uni` 模块.
