### ISSUE TITLE
微信小程序下使用的问题

### ISSUE THREAD

**Issue by neohan666** [lipingruan/fucking-util-signature-uni#3]
1、npm构建后的fucking-util-signature-uni/index.js会报“以下文件体积超过 500KB，已跳过压缩以及 ES6 转 ES5 的处理”。
2、同样由于体积过大，主包大小很容易超过2Mb的限制。

**Comment by lipingruan** [comment]
小程序环境诸多函数不支持

目前没有好的方式可以替代

超过2MB限制可以分包处理

最好小程序图片都放网络上
